# Generated by Django 5.0.2 on 2024-02-13 19:49

import config.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2024)),
                ('description', models.TextField()),
                ('genres', models.TextField()),
                ('poster', models.ImageField(upload_to=config.helpers.convert_poster_name)),
                ('video', models.FileField(upload_to=config.helpers.convert_file_name)),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
    ]
